# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbmdata',
            name='acting_knowledge',
            field=models.BooleanField(default=False, help_text='Acting on his/her knowledge of student learning', verbose_name='Acting on knowledge'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='aspiration_feedback',
            field=models.BooleanField(default=False, help_text='Delivering feedback that is aspirational', verbose_name='Aspirational feedback'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='clarifying_lp',
            field=models.BooleanField(default=False, help_text='Making learning progressions clear to students', verbose_name='Clarifying learning progressions'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='demonstrating_care',
            field=models.BooleanField(default=False, help_text='Demonstrating to student(s) that he/she cares about their learning', verbose_name='Relational trust'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='dialogue',
            field=models.BooleanField(default=False, help_text='Engaged in dialogue with students', verbose_name='Engaged in dialogue'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='evaluating_effect',
            field=models.BooleanField(default=False, help_text='Evaluating the effect he/she is having on students learning', verbose_name='Evaluating effect'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='focus_learning',
            field=models.BooleanField(default=False, help_text='Managing classroom so learning is focus, not behaviour', verbose_name='Focussing on learning'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='high_exp',
            field=models.BooleanField(default=False, help_text='Setting and demonstrating high expectations', verbose_name='High expectations'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='jit_feedback',
            field=models.BooleanField(default=False, help_text='Delivering feedback just in time', verbose_name='Just in time'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='learning_evidence',
            field=models.BooleanField(default=False, help_text='Gathering evidence of student progress or learning', verbose_name='Gathering Evidence'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='other',
            field=models.CharField(blank=True, default='', help_text='Please be specific', max_length=1000, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='peer_feedback',
            field=models.BooleanField(default=False, help_text='Working with students to ensure peer feedback is accurate', verbose_name='Peer feedback'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='praise',
            field=models.BooleanField(default=False, verbose_name='Praise'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='process_feedback',
            field=models.BooleanField(default=False, help_text='Process feedback to students who are becoming more proficient', verbose_name='Process feedback'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='providing_challenge',
            field=models.BooleanField(default=False, verbose_name='Providing challenge'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='providing_feedback',
            field=models.BooleanField(default=False, help_text='Providing feedback to students', verbose_name='Providing feedback'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='range_strategies',
            field=models.BooleanField(default=False, help_text='Using a wide range of instructional strategies', verbose_name='Wide range of strategies'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='safe_classroom',
            field=models.BooleanField(default=False, help_text='Ensuring it is safe to make mistakes', verbose_name='Safe classroom'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='seeking_feedback',
            field=models.BooleanField(default=False, help_text='Seeking feedback from students', verbose_name='Seeking feedback'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='sharing_understanding',
            field=models.BooleanField(default=False, help_text='The student(s) are sharing their understanding of learning', verbose_name='Students sharing understanding'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='sr_feedback',
            field=models.BooleanField(default=False, help_text='Self-regulation feedback to students with high proficiency', verbose_name='Self-regulation feedback'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='task_feedback',
            field=models.BooleanField(default=False, help_text='Task feedback to students learning something new', verbose_name='Task feedback'),
        ),
        migrations.AddField(
            model_name='mbmdata',
            name='whw_feedback',
            field=models.BooleanField(default=False, help_text='Feedback answers "Where am I going", "How am I going", "Where next"', verbose_name='Where, how, where next'),
        ),
    ]
