# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-17 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbinteraction',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='observations.FeedbackObservation'),
        ),
    ]
