# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionobservation',
            name='observation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='observations.Observation'),
            preserve_default=False,
        ),
    ]
