# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_interactionobservation_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionobservation',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='interactionobservation',
            name='position',
        ),
        migrations.AddField(
            model_name='interactionobservation',
            name='minute',
            field=models.IntegerField(default=0, help_text='How many minutes into the lesson is this observation?', verbose_name='Timing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interactionobservation',
            name='evidenceDIPS',
            field=models.CharField(blank=True, default='', help_text='Evidence of discursive interactions and power sharing strategies', max_length=2000, verbose_name='Discursive/power sharing'),
        ),
        migrations.AlterField(
            model_name='interactionobservation',
            name='teacherloc',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('S', 'Stationary'), ('I', 'Moving around room'), ('O', 'Out of room')], default='', max_length=1, verbose_name='Teacher Location'),
        ),
    ]
