# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-09 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_auto_20170309_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionobservation',
            name='intcode',
            field=models.CharField(blank=True, choices=[('P', 'Prior learning'), ('FB', 'Feedback on learning'), ('FF', 'Feed-forward support'), ('Co', 'Co-construction')], default='', max_length=2, verbose_name='Interaction Type'),
        ),
        migrations.AlterField(
            model_name='interactionobservation',
            name='evidenceDIPS',
            field=models.CharField(blank=True, default='', help_text='Evidence of discursive interactions and power sharing strategies', max_length=2000, verbose_name='Power sharing'),
        ),
        migrations.AlterField(
            model_name='interactionobservation',
            name='studentint',
            field=models.CharField(blank=True, choices=[('I', 'Indigenous or minoritised student'), ('O', 'Interaction with other student')], default='', help_text='Which students are the teacher interacting with?', max_length=1, verbose_name='Group Interactions'),
        ),
    ]
