# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-09 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20170309_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionobservation',
            name='intcode',
            field=models.CharField(blank=True, choices=[('', 'NA'), ('P', 'Prior learning'), ('FB', 'Feedback on learning'), ('FF', 'Feed-forward support'), ('Co', 'Co-construction')], default='', max_length=2, verbose_name='Interaction Type'),
        ),
        migrations.AlterField(
            model_name='interactionobservation',
            name='teacherloc',
            field=models.CharField(blank=True, choices=[('', 'NA'), ('S', 'Stationary'), ('I', 'Moving around room'), ('O', 'Out of room')], default='', max_length=1, verbose_name='Teacher Location'),
        ),
    ]
