# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20170309_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter observation date', verbose_name='Observation Date'),
        ),
    ]
