# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-10 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20170309_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionobservation',
            name='minute',
            field=models.IntegerField(help_text='How many minutes into the lesson is this observation?', verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='interactionobservation',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactionobservations', to='observations.Observation'),
        ),
    ]
