# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-10 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_auto_20170310_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Enter observation date', verbose_name='Observation Date'),
        ),
    ]
