# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-10 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_auto_20170310_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactionobservation',
            options={'verbose_name': 'interactionobservation', 'verbose_name_plural': 'interactionobservations'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': 'observation', 'verbose_name_plural': 'observations'},
        ),
    ]
